name: Run Python Script

on:
  push:
    branches:
      - main  # Change this to your target branch, e.g., "main" or "master"
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub UI

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Specify the virtual environment (Ubuntu in this case)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # This checks out your code from the GitHub repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can specify any Python version you need, such as '3.8' or '3.10'

    - name: Monitor RAM and CPU usage
      run: |
        echo "Initial Memory and CPU usage:"
        free -h  # Shows memory usage
        top -n 1  # Shows CPU usage

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # This installs the dependencies listed in requirements.txt


    - name: Monitor RAM and CPU usage after install
      run: |
        echo "Memory and CPU usage after installation:"
        free -h
        top -n 1


    - name: Run Python script
      env:
       OWM_API_KEY: ${{ secrets.OWM_API_KEY }} 
      run: python final.py  # Replace 'your_script.py' with the name of your Python script

      
    - name: Monitor RAM and CPU usage after running script
      run: |
        echo "Memory and CPU usage after running the script:"
        free -h
        top -n 1

      
